### ISSUE TITLE
First phase reason string support

### ISSUE THREAD

**Issue by jacqueswww** [ethereum/vyper#889] opened 2018-06-12 11:42 UTC
This is the suggested template for new VIPs.

## Preamble

    VIP: 889
    Title: First phase reason string support
    Author: Jacques Wagener
    Type: Standard Track
    Status: Draft
    Created: 2018-6-12
    Requires (*optional): <VIP number(s)>
    Replaces (*optional): <VIP number(s)>

## Simple Summary
Revert opcode allows additional information to best sent on an `assert`, `throw` or `overflow/clamp`.
This VIP adds first phase support for the `assert` statement.

## Abstract

Providing 2 values to the `assert` statement should allow user to write an error message.

## Motivation
Following the discussions in https://github.com/ethereum/EIPs/issues/838. We can already produce compatible error statements, greatly enhancing the "tx-failed oh my expierence". 

## Specification

When supplying an assert error message

```python
assert 1 != 2, "special error message"
```
Should produce, ABI function signature: `Error(string)`.

https://github.com/ethereum/EIPs/issues/838#issuecomment-379238333

## Backwards Compatibility
Since this a forwards feature and doesn't break any existing changes, this can be part 

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by ben-kaufman** [comment] 2018-06-12 11:56
That’s a great feature but I don’t really like the syntax. I think of something like:
```
assert 1 < 2 else "special error message"
```
```
assert 1 < 2 catch "special error message"
```
What do you think?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jacqueswww** [comment] 2018-06-12 12:02
I chose `asset 1 < 2, ""` because it follows python.

**Comment by jacqueswww** [comment] 2018-06-18 14:47
Approved.

**Comment by jacqueswww** [comment] 2018-06-25 17:02
Vyper side is mostly done on this, busy investigating how I can add this to py-evm so the reason string can be retrieved.

**Comment by haydenadams** [comment] 2018-08-20 06:47
@jacqueswww  Sorry for even asking I know you're busy, but any chance this can be merged by ~Sept 1? 

Uniswap (Vyper dex) needs a code freeze before formal verification. Would love to have error messages make the cut! 

Not even going to ask about https://github.com/ethereum/vyper/issues/901 since theres no way lol

**Comment by jacqueswww** [comment] 2018-08-20 07:10
Sure thing, should be working with the newer eth tester  which is what this was waiting for ;)

**Comment by fubuloubu** [comment] 2018-08-20 14:55
@haydenadams you can add the strings now, it will parse (but not do anything).

Then when Jacques updates the parser to add support for generating this output, it can be regression tested versus the newest version of the compiler to see the version strings in action (and that it hasn't changed the code functionally).

Same goes to #901 actually. We have made the user-breaking changes already IIRC.

**Comment by fubuloubu** [comment] 2018-08-21 02:30
fair enough, it is probably better only to add the strings when the associated feature becomes available.

still, a regression against a newer version of a compiler (with small feature additions like reason strings) is much cheaper than a full first audit. you will probably go through several with your first version of code if you do any redeployments to fix bugs with usage. (p.s. you should have a plan for that if you don't already)

**Comment by haydenadams** [comment] 2018-08-21 03:26
Yeah for sure, there will def be bug fixes/changes made during the process. Limited budget + deadline (hoping to launch ahead of Devcon4) so I'm trying to minimize them as much as possible!

**Closed** 2018-09-06 22:43 UTC
Labels: Approved, discussion
