### ISSUE TITLE
VIP: Contract data type

### ISSUE THREAD

**Issue by DavidKnott** [ethereum/vyper#541] opened 2017-12-04 14:10 UTC
## Preamble

    VIP: <to be assigned>
    Title: Contract data type
    Author: David Knott
    Type: Standard Track
    Status: Draft
    Created: 2017-12-4

## Simple Summary
"If you can't explain it simply, you don't understand it well enough." Provide a simplified and layman-accessible explanation of the VIP.
Having a contract data type will allow users to save addresses to be used with contracts,

## Abstract
Right now making external contract calls requires passing in an address to an external contract each time, this is somewhat inefficient and could be confusing to newcomers.

## Motivation
Having a contract data type will make it easier for users to make external contract calls and easier for Viper to ensure that the user is making the external contract call they intend to be making.

## Specification
```
    contract_1 = """
@public
def bar() -> num:
    return 1
"""

    contract_2 = """
class Bar():
    def bar() -> num: pass

bar_contract: Bar

@public
def foo(contract_address: contract(Bar)) -> num:
    self.bar_contract = contract_address
    return self.bar_contract.bar()
    """

    c1 = get_contract(contract_1)
    c2 = get_contract(contract_2)
    assert c2.foo(c1.address) == 1
```

## Backwards Compatibility
As of now this is backwards compatible but I'd like to make this the only way that external contract calls are made to simplify the process as much as possible (this would be a breaking change).

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by fubuloubu** [comment] 2017-12-04 15:26
Sorta duplicate of #537. Condense

**Closed** 2018-01-15 15:44 UTC
Labels: Approved, Done, Feature, discussion
