### ISSUE TITLE
Fake return values from stack.

### ISSUE THREAD

**Issue by Dexaran** [ethereum/vyper#330] opened 2017-09-02 17:59 UTC
In Solidity, if you call a function that does not return a value, assuming that it returns something, you will get fake return values from the stack. Not unassigned value or error.

I think that it is a serious issue because we can't rely on return values at all. It would be better to throw an error or return unassigned values.

I have described this in [solidity issue #2630](https://github.com/ethereum/solidity/issues/2630).

Is here any possibility to avoid the same problem in Viper?

**Comment by DavidKnott** [comment] 2017-09-02 20:06
@Dexaran You're on it!  This is a huge problem, I'll start by trying to come up with a failing test case today similar to the one you made in Solidity.

**Comment by fubuloubu** [comment] 2017-09-02 22:42
As a fancier solution, implementing a basic verification stage type checking all return values in the function's control flow path would be useful to provide programmer feedback to a bad contract.

**Comment by jacqueswww** [comment] 2018-06-13 12:16
Adding this to Fix up the beta project, so some time can be taken to investigate and see if we can avoid this.

**Comment by haydenadams** [comment] 2018-06-14 08:22
@jacqueswww  @DavidKnott  You should be careful here: https://github.com/ethereum/solidity/issues/4116


Many ERC20 contracts including [OMG](https://etherscan.io/address/0xd26114cd6EE289AccF82350c8d8487fedB8A0C07#code) do not return booleans as specified in the ERC20 standard. If you have a contract with a common interface for all ERC20s that expects boolean return values for `transfer()`, `approve()`, and `transferFrom()` and enforce that any call using that interface has to return either True or False, all calls to the OMG token contract (and several other tokens) will revert. This is problematic for many DEX designs.

**Comment by fubuloubu** [comment] 2018-06-14 17:32
Interfaces should be implemented exactly as designed, :100: agree on that. I am curious if the random stack value return influences this at all because sometimes the value will be non-zero, and that would be difficult to debug. Your suggestion to enforce call return values as the interface specifies should absolutely be enforced.

I don't know if this solves the problem here though, as the OP notes it will return without throwing random values from the stack.

**Comment by haydenadams** [comment] 2018-06-14 18:15
@fubuloubu I wasn't necessarily suggesting it. I was saying if it is enforced over 130 tokens currently on EtherDelta will no longer be able to be transferred using the standard ERC20 interface.

**Comment by jacqueswww** [comment] 2018-06-19 15:17
I investigated this some more, and because we use `CALL` and don't have a in memory stack like solidity. In it's current iteration vyper can not have this issue.
However this is something to consider when we make a decision with regards to #901 .

**Closed by jacqueswww** 2018-06-19 15:17 UTC
Labels: discussion
