### ISSUE TITLE
Unable to deploy Vyper contract to Ethereum TestRPC (Ganache CLI) 

### ISSUE THREAD

**Issue by ltfschoen** [ethereum/vyper#784] opened 2018-04-19 04:28 UTC
* vyper Version: 0.0.4
* pyethereum Version: N/A
* OS: osx (macOS 10.12.6
* Python Version (python --version): `Python 3.6.2`
* Environment (output of `pip freeze`):
```
aiohttp==2.3.10
asn1crypto==0.21.0
async-lru==0.1.0
async-timeout==1.2.0
attrdict==2.0.0
attrs==17.4.0
certifi==2017.4.17
cffi==1.7.0
chardet==3.0.2
coincurve==7.0.0
coverage==4.5.1
cryptography==2.2.2
cytoolz==0.9.0.1
eth-abi==1.0.0
eth-account==0.1.0a2
eth-bloom==1.0.0
eth-hash==0.1.1
eth-keyfile==0.5.1
eth-keys==0.2.0b3
eth-rlp==0.1.0
eth-tester==0.1.0b21
eth-utils==1.0.1
ethereum==2.3.1
future==0.16.0
hexbytes==0.1.0
idna==2.5
idna-ssl==1.0.0
lru-dict==1.1.6
more-itertools==4.1.0
multidict==4.0.0
pbkdf2==1.3
pluggy==0.6.0
py==1.5.3
py-ecc==1.4.2
py-evm==0.2.0a12
pycparser==2.18
pycryptodome==3.6.1
pyethash==0.1.27
pypandoc==1.4
pysha3==1.0.2
pytest==3.5.0
pytest-cov==2.5.1
pytest-runner==4.2
PyYAML==3.12
repoze.lru==0.7
requests==2.18.4
rlp==0.6.0
scrypt==0.8.6
semantic-version==2.6.0
six==1.10.0
toolz==0.8.0
trie==1.3.4
urllib3==1.21.1
vyper==0.0.4
web3==4.1.0
websockets==4.0.1
yarl==1.0.0
```

### What's your issue about?

I created this Python script https://github.com/ltfschoen/vyper-test/blob/master/scripts/main.py, which is a mixture of code that I created after reviewing the vyper repo, but ultimately uses Web3.py to try to deploy a Vyper contract to Ganache CLI (which I have running on localhost:8545). It runs successfully up to the `.deploy` line of code and then it hangs, but doesn't show any error message in the terminal, and I do not see any transaction in the Ganache CLI terminal:
```
...
tx_hash = contract_instance_web3.deploy(transaction={'from': web3.eth.accounts[0], 'gas': 410000})
print("Deployed Contract Tx Hash: %s", tx_hash)
...
```

I started Ganache CLI with the following command in a separate terminal window:
```bash
ganache-cli \
    --account="0x0000000000000000000000000000000000000000000000000000000000000001, 2471238800000000000" \
    --account="0x0000000000000000000000000000000000000000000000000000000000000002, 4471238800000000000" \
    --unlock "0x0000000000000000000000000000000000000000000000000000000000000001" \
    --unlock "0x0000000000000000000000000000000000000000000000000000000000000002" \
    --blocktime 0 \
    --deterministic true \
    --port 8545 \
    --hostname localhost \
    --seed 'blah' \
    --debug true \
    --mem true \
    --mnemonic 'something' \
    --db './db/chain_database' \
    --verbose \
    --networkId=3 \
    --gasLimit=7984452 \
    --gasPrice=20000000000;
```

Please include information like:

### How can it be fixed?

Try using my code by following these instructions to https://github.com/ltfschoen/vyper-test#chapter-0---setup-without-docker-

Ideally a link to instructions or an example of how to deploy a Vyper smart contract to TestRPC, Ganache CLI, Ropsten, Rinkeby, or Mainnet would be great.

#### Cute Animal Picture

*****************
***   L__    ___|    **
**           U           **
********V********

**Comment by fubuloubu** [comment] 2018-04-19 04:34
You get bytecode/abi and load it into `contract_instance_web3`, right?

This means the problem is with web3 -> ganache

**Comment by ltfschoen** [comment] 2018-04-19 12:31
Thanks. I'll try using web3.py and Geth instead similar to how I did it here for Solidity but for Vyper instead https://github.com/ltfschoen/geth-node/blob/master/scripts/main.py

**Comment by fubuloubu** [comment] 2018-04-19 14:02
It would be really cool to get it working for ganache and truffle. If you can copy how it currently does sold -> ganache and expand that so it leverages vyper in the same way, we should be in business.

I don't think it uses web3py for that. You don't have to use python to work with vyper, the compiler binary will work just as well as sold can (and if it doesn't we can add compiler flags and output options)

**Comment by ltfschoen** [comment] 2018-04-19 22:31
I've made changes to the web3.py script https://github.com/ltfschoen/vyper-test/blob/master/scripts/main.py and updated its README https://github.com/ltfschoen/vyper-test/#chapter-0---setup-without-docker- to show how to successfully deploy a Vyper contract to a Private Network using Geth, and view the transaction in the Geth logs

**Comment by jacqueswww** [comment] 2018-06-12 11:15
Closing for now, but placing `vyper-test` repo/chapters on our resource page.

Thanks! 
:smile_cat:

**Closed by jacqueswww** 2018-06-12 11:15 UTC
