### ISSUE TITLE
VIP: Require compiler flag for nonstandard primitive types

### ISSUE THREAD

**Issue by daniel-jozsef** [ethereum/vyper#750] opened 2018-04-03 09:53 UTC
Apparently Vyper has primitive types outside the ones discussed in the documentation. See #720 #722 apparently "signed256" was a thing, and now we have "int256", which is a type distinct from uint256.

I get that sometime you may need these for interoperability with Solidity contracts, but it can be confusing, hurt auditability, and may result in the shit type system of Solidity slowly migrating over into Vyper.

### How can it be fixed?

I propose two measures to protect the integrity of Vyper from "compatibility types", while maintaining support for them in the cases when they are neded.

1. Rename all "compatibility" types, prefixing them with COMPAT_ or compat_. So int256 should become COMPAT_int256.

2. Throw compiler errors on these types, requiring a command line flag --allow-compat-types to compile source that makes use of them.

#### Cute Animal Picture

![Rainbow lorikeets](https://www.omlet.co.uk/images/originals/rainbow-lorikeet-pair.jpg)

**Comment by fubuloubu** [comment] 2018-04-03 13:49
We eventually need to support the full type system if we want to maintain full compatibility as an EVM language, that's why we renamed `num` to `int128`. I DON'T think this is a good idea with that consideration in mind. We currently only have full support for some basic types because it was easier to get things up and running with fewer types.

**Comment by daniel-jozsef** [comment] 2018-04-03 17:30
[I'm not so sure about that...](http://lll-docs.readthedocs.io/en/latest/lll_abi.html)

> Each of the elementary types listed in the ABI specification is represented in the call data as a 32 byte word.

The thing is, from what I gather, the ABI spec is the ABI spec, and the EVM is the EVM. The EVM knows 32-bit words, and that's it. The way Solidity does uint8 is by ignoring the 31 most significant bytes.

I really don't see why supporting all these types as first class citizens would be necessary. Sure to interface with legacy contracts, but then you could always OR out the 31 msB's from a uint256, and effectively have a uint8.

I think it's okay to guide the hand of the developers, and mark some ABI types as first class citizens, and all the others as "well if you REALLY want them, but know that this is not Vyperic".

Packing structs is one legitimate use for smaller types, but let's think a bit longer about that.

**Comment by fubuloubu** [comment] 2018-04-03 19:26
My mistake, I misspoke about EVM compatibility, I more meant any compiled language that compiles to EVM. You're 100% right about packing structs and compatibility to standards like ERC20 being the only use of other types from our basic `int128` we use as a first class citizen. The way most staticly typed languages that compile to assembly operate in a similar fashion, by ignoring unused bits unless they can leverage it for optimizations i.e. packed structs.

The problem is that we are working with a fairly low-level language, and it's so much more complex because you're implementating such high level logic in the, there's a bit of a disconnect there IMO.

The best thing that we could do long term is support all integer types, allowing for optimizations to save gas usage, but have a default like `int` (which aliases to `int128`) which everyone can use, unless they're looking to optimize.

But yeah, this is pretty complicated. Unless we built in a variable sized integer like python has and optimized the usage size based on some static analyzer to reduce gas usage, it's probably really up for debate what we support.

**Comment by daniel-jozsef** [comment] 2018-04-04 09:28
Btw, I've been wondering what the reason was behind using 128 bit integers for signed numbers (as opposed to 256 bit ones).

Was it because they were originally named num128 and num256?

---

As for ABI compatibility, a larger unsigned int will always be compatible with a smaller one (and a larger unsigned int too, in [0..MAXINT], as an uint8 is nothing but a uint256 that is smaller than 256...

Structs... packing them can really introduce issues, it can be super dangerous... So I guess the code for that would have to be seriously audited.

**Comment by jacqueswww** [comment] 2018-04-09 14:31
As discussed, we will look at this in detail (type systems, packing etc.) after beta launch.

**Comment by jacqueswww** [comment] 2018-12-06 13:55
I am closing this as int256 was removed, and this can be re-looked at if needed, I would rather opt for going in a direction of implementing the additional types if necessary (or a standardised convert on the function definition) - than half-baked compatiblity checks.

**Closed by jacqueswww** 2018-12-06 13:55 UTC
Labels: discussion, post beta
