### ISSUE TITLE
Assignment to tuple not supported

### ISSUE THREAD

**Issue by denis-bogdanas** [ethereum/vyper#727] opened 2018-03-29 13:25 UTC
This code won't compile:

    @public
    def out_literals() -> (int128, address, bytes <= 4):
        return 1, 0x0000000000000000000000000000000000000000, "random"

    @public
    def test():
        a: int128
        b: address
        c: bytes <= 4
        (a, b, c) = self.out_literals()

Without assignment to tuples it's impossible to actually call a method that returns a tuple from the same contract. All tests for tuple carefully avoid this scenario.

**Comment by jacqueswww** [comment] 2018-04-03 16:00
This is a duplicate of https://github.com/ethereum/vyper/issues/605 I belive, currently slated as post-beta.
Will add it to next weeks agenda, so we can consider post/pre beta on this ;)

**Comment by jacqueswww** [comment] 2018-04-17 10:14
Starting on this.

**Comment by jacqueswww** [comment] 2018-06-14 09:20
This has been fixed. :smile:

**Closed by jacqueswww** 2018-06-14 09:20 UTC
Labels: Approved, duplicate
