### ISSUE TITLE
Add Integration to Remix IDE for Vyper

### ISSUE THREAD

**Issue by fubuloubu** [ethereum/vyper#529] opened 2017-11-29 15:40 UTC
### What's your issue about?
It would be awesome if the viper online compiler [viper.tools](http://viper.tools) integrated some of the Remix functionality for deployment of bytecode and creating transactions/interacting with deployed contracts.

Conversely, if we could integrate the viper online compiler as an option in Remix, that would be awesomer!

I can make this a VIP if necessary

**Comment by fubuloubu** [comment] 2018-01-19 01:14
@DavidKnott I would really like to see this issue be "pre beta", it's the best way to teach newcomers

**Comment by DavidKnott** [comment] 2018-01-19 04:51
I think having this as "pre beta" could slow things down a lot, I still don't know of a good way to run python in the browser.

**Comment by fubuloubu** [comment] 2018-01-19 17:57
Heroku? Doesn't scale but...

**Comment by DavidKnott** [comment] 2018-01-20 18:03
A nice heroku Remix IDE would be great for helping people get into Vyper.  I think we'd have to make it super clear though that they shouldn't use the IDE for real world deployment (like Solidity Remix) until we've figured out how to run Vyper in the browser.

**Comment by fubuloubu** [comment] 2018-01-20 21:23
I personally wouldn't use remix for that either lol

**Comment by holgerd77** [comment] 2018-02-10 08:07
Maybe it is also possible to compile ``Vyper`` from ``Python`` to ``WebAssembly``, there are some people experimenting with ``Python`` in this regard, not sure how far this is:
https://stackoverflow.com/questions/44761748/compiling-python-to-webassembly

We have some good people with broad Emscripten/WASM knowledge also doing the eWASM VM over on the EthereumJS team.

**Comment by fubuloubu** [comment] 2018-02-10 20:01
Ah, that's a great option! Have to look into it. I know our module isn't too crazy, but have to see about our dependencies

**Comment by jacqueswww** [comment] 2018-06-13 12:21
Duplicate of #278.

**Closed by jacqueswww** 2018-06-13 12:21 UTC
