### ISSUE TITLE
Return a list as a part of a tuple 

### ISSUE THREAD

**Issue by khotkevych** [ethereum/vyper#593] opened 2017-12-20 09:59 UTC
* viper Version: 0.0.2

### What's your issue about?

Viper currently doesn't support returning a list as a part of a tuple.
Next code returns the _"Can't return type %s as part of tuple"_ error.

`@public`
`@constant`
`def test() -> (num[5], bool):`
    `test_list = [1,2,3,4,5]`
  `  return (test_list, false)` 

#### Cute Animal Picture

> 
![cute-tapir](https://user-images.githubusercontent.com/13405635/34201435-25d3ca86-e57d-11e7-9afd-890004b8b3a6.jpg)

**Comment by jakerockland** [comment] 2018-02-17 01:11
@DavidKnott @jacqueswww @fubuloubu is this something that should be implemented? I was starting to work on a fix for this as a way of getting myself familiarized with the Vyper codebase.

**Comment by fubuloubu** [comment] 2018-02-17 04:44
I see no problem, as long as it's a static array (not that we allow otherwise lol)

**Comment by jakerockland** [comment] 2018-02-17 07:18
Awesome, will get started on this then.

**Comment by jacqueswww** [comment] 2018-02-17 09:03
@jakerockland you might know this already, but there is an important little tid bit to know on static arrays -they don't form part of the dynamic section of the return bytes. However they are just placed straight into the static part. For logging there is a pack_args_by_32 function which handles list types which should also help in understanding how to do it :smile_cat: 

http://solidity.readthedocs.io/en/develop/abi-spec.html

**Comment by jacqueswww** [comment] 2018-02-17 09:04
Also what is useful sometimes tracing & reading pyethereum abi handling code: https://github.com/ethereum/pyethereum/blob/develop/ethereum/abi.py

**Comment by jakerockland** [comment] 2018-02-17 17:37
@jacqueswww Thank you very much for this. May take me a little bit for this PR. While I have a decent foundational understanding of computer language design and compiler design, this is my first diving into Vyper aside from the tutorial examples and I haven't played with Solidity much. Really appreciate you pointing me to these resources! 😄

**Comment by jacqueswww** [comment] 2018-08-01 14:43
Duplicate of https://github.com/ethereum/vyper/issues/955

**Closed by jacqueswww** 2018-08-01 14:43 UTC
