### ISSUE TITLE
Refactor conversion tests from `test_bytes` to `test_convert_bytes32` and `test_convert_bytes`

### ISSUE THREAD

**Issue by jakerockland** [ethereum/vyper#1084] opened 2018-11-15 15:32 UTC
### Version Information

* vyper Version: 0.1.0b4

### What's your issue about?

Currently the tests for testing type conversion are spread across different files corresponding to either the type being converted from, or the type being converted to. This is a bit confusing for adding new functionality/reviewing the tests as it is unclear if the tests should be in the test file for the type being converted from or that being converted to.

### How can it be fixed?

We create a new test file `test_type_conversions.py` in the `types` test directory and refactor all related type conversion tests to be located there.

#### Cute Animal Picture

![image](https://user-images.githubusercontent.com/8602661/48563210-083ef800-e8b1-11e8-8870-fad6746de9c0.png)

**Comment by fubuloubu** [comment] 2018-11-15 15:38
Sounds good to me! Conversions are a feature, not a bug 🤣

**Comment by jakerockland** [comment] 2018-11-15 16:14
Rad, I'll do this after #1077, #1082, and #1085 are all ready for merge to avoid merge conflicts haha.

**Comment by jacqueswww** [comment] 2018-11-16 08:36
Works for me :+1:

**Comment by jacqueswww** [comment] 2018-11-27 12:37
Merged PR.

**Closed by jacqueswww** 2018-11-27 12:37 UTC
