### ISSUE TITLE
VIP:  Add built-in function for Merkle Proof  Membership Checks

### ISSUE THREAD

**Issue by DavidKnott** [ethereum/vyper#482] opened 2017-11-18 19:24 UTC
## Preamble

    VIP: <to be assigned>
    Title: Built in Merkle Proof support
    Author: David Knott
    Type: Standard
    Status: Draft
    Created: 2017-11-18

## Simple Summary
Add a built-in function for merkle proofs that could be used to easily check for membership.

## Abstract
Right now users have to hand roll their own merkle proof checker, I propose supporting merkle proofs natively as they are used in many different areas of development.
For more information on merkle trees look [here](https://www.codeproject.com/Articles/1176140/Understanding-Merkle-Trees-Why-use-them-who-uses-t).

## Motivation
Merkle proofs are used often enough that I don't think it makes sense for developers to keep reinventing the wheel or to use external libraries.  I think this is particularly relevant for Viper given that Viper doesn't support inheritance or libraries.

## Specification
I propose implementing a built-in function that'd look like this:
```
check_merkle_membership(root_hash, hash_being_checked, proof_of_inclusion) => bool
```
Behind the scenes it'd implement the functionality performed in this [smart contract](https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/MerkleProof.sol).

## Backwards Compatibility
This would be new functionality and would not introduce compatibility issues other then `check_merkle_membership` becoming a reserved.

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by fubuloubu** [comment] 2017-11-18 19:58
Do you have some smart contract use cases for referencing? It's not obvious to me why this is useful in a Smart Contract context, unless you're building something pretty complicated like git on the blockchain.

**Comment by fubuloubu** [comment] 2017-11-18 20:03
Also, as a side note, that article made me realize that you could probably create plugin for git that chains together commit hashes to prove the history was not modified. I thought it would probably have to be a totally separate system. Very cool!

**Comment by fubuloubu** [comment] 2018-10-19 15:19
Duplicate of #806

**Closed by fubuloubu** 2018-10-19 15:19 UTC
Labels: discussion, post beta
